# Generated by Django 4.2.13 on 2024-08-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackGroundModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='background')),
            ],
        ),
        migrations.CreateModel(
            name='BasicInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('image', models.ImageField(default='image/user.jpeg', upload_to='image')),
                ('birthday', models.DateField()),
                ('about_me', models.TextField()),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('freelance', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Unavailable', max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=255)),
                ('entertainment', models.CharField(max_length=255)),
                ('degree', models.CharField(choices=[("Associate's", "Associate's"), ("Bachelor's", "Bachelor's"), ("Master's", "Master's"), ('Doctorate', 'Doctorate'), ('Professional', 'Professional'), ('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('High School', 'High School')], max_length=12)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
