# Generated by Django 4.2.13 on 2024-08-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Summary',
        ),
        migrations.AddField(
            model_name='basicinformationmodel',
            name='summary',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
