# Generated by Django 4.2.8 on 2024-01-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='response',
            field=models.BooleanField(default=False),
        ),
    ]
