# Generated by Django 4.2.13 on 2024-08-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_delete_summary_basicinformationmodel_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('from_date', models.DateField()),
                ('until_date', models.DateField()),
            ],
            options={
                'ordering': ['from_date'],
            },
        ),
    ]
