# Generated by Django 4.2.8 on 2024-01-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_create_date_contact_receive_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='response_date',
            field=models.DateTimeField(),
        ),
    ]
