# Generated by Django 4.2.13 on 2024-08-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_educationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationmodel',
            name='from_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='until_date',
            field=models.IntegerField(),
        ),
    ]
