# Generated by Django 4.2.13 on 2024-08-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_educationmodel_from_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationmodel',
            options={'ordering': ['-from_date']},
        ),
        migrations.AddField(
            model_name='educationmodel',
            name='major',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
