# Generated by Django 4.2.8 on 2024-01-10 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_contact_response_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['create_date']},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='receive_date',
            new_name='create_date',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='response',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='response_date',
        ),
    ]
