# Generated by Django 4.2.13 on 2024-08-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_educationmodel_options_educationmodel_major'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalExperienceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('compony', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('from_date', models.IntegerField()),
                ('to_date', models.IntegerField()),
            ],
            options={
                'ordering': ['-from_date'],
            },
        ),
        migrations.RenameField(
            model_name='educationmodel',
            old_name='until_date',
            new_name='to_date',
        ),
    ]
