# Generated by Django 4.2.8 on 2024-08-04 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_basicinformationmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicinformationmodel',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['created_date']},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='basicinformationmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basicinformationmodel',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
