# Generated by Django 4.2.13 on 2024-08-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_professionalexperiencemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinformationmodel',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='from_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='to_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professionalexperiencemodel',
            name='from_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professionalexperiencemodel',
            name='to_date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
