# Generated by Django 4.2.13 on 2024-08-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_basicinformationmodel_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalexperiencemodel',
            name='jobـdescription',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
