# Generated by Django 4.2.14 on 2024-08-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_professionalexperiencemodel_jobـdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinformationmodel',
            name='first_name_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basicinformationmodel',
            name='first_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basicinformationmodel',
            name='first_name_fa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basicinformationmodel',
            name='last_name_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basicinformationmodel',
            name='last_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basicinformationmodel',
            name='last_name_fa',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
